<a href="https://colab.research.google.com/github/AshleyBrooks213/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Ashley_Brooks_DS21_UNIT1Sprint3MOD4_Copy_of_LS_DS_134_Linear_Algebra_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Objectives:
- define a vector and calculate a vector length and dot product
- define a matrix and calculate a matrix dot product, transpose, and inverse
- explain cosine similarity and compute the similarity between two vectors
- use linear algebra to solve for linear regression coefficients

#Use the following information to answer the assignment questions 1) - 11).

###Is head size related to brain weight in healthy adult humans?

The Brainhead.csv dataset provides information on 237 individuals who were subject to post-mortem examination at the Middlesex Hospital in London around the turn of the 20th century. Study authors used cadavers to see if a relationship between brain weight and other more easily measured physiological characterizes such as age, sex, and head size could be determined. The end goal was to develop a way to estimate a person’s brain size while they were still alive (as the living aren’t keen on having their brains taken out and weighed). 

**We wish to determine if we can improve on our model of the linear relationship between head size and brain weight in healthy human adults.**

Source: R.J. Gladstone (1905). "A Study of the Relations of the Brain to the Size of the Head", Biometrika, Vol. 4, pp105-123.

In [15]:
#Import the Brainhead.csv dataset from a URL and print the first few rows

import pandas as pd
import numpy as np


data_url = 'https://raw.githubusercontent.com/LambdaSchool/data-science-practice-datasets/main/unit_1/Brainhead/Brainhead.csv'

df = pd.read_csv(data_url, skipinitialspace=True, header=0)

df.head()

Gender  Age  Head  Brain
0       1    1  4512   1530
1       1    1  3738   1297
2       1    1  4261   1335
3       1    1  3777   1282
4       1    1  4177   1590

1) Store the response variable - brain size - as a matrix called Y.

In [17]:
### YOUR CODE HERE ###

Y = np.array(df['Brain']).reshape(-1, 1)

2) Store the explanatory variable - head size size - as a matrix called X.  Don't forget to include the column of 1s for the intercept term.

In [18]:

### YOUR CODE HERE ###

Head = np.array(df['Head']).reshape(-1, 1)

ones = np.repeat(1, len(df)).reshape(-1, 1)

X = np.concatenate((ones, Head), axis=1)


3) Calculate $X^T$.  Explain what the transpose of a matrix is.

In [19]:
### YOUR CODE HERE ###

X_T = np.transpose(X)



Answer: **A transpose matrix is one whose rows are the columns of the original and vice versa.**

4) Use matrix multplication to calculate $X^TX$

In [20]:
### YOUR CODE HERE ###

X_T_X = np.matmul(X_T, X)

print(X_T_X)

[[       237     861256]
 [    861256 3161283190]]


5) Calculate $(X^TX)^{-1}$.  Explain what the inverse of a matrix is.

In [21]:
### YOUR CODE HERE ###

X_T_X_inv = np.linalg.inv(X_T_X)

print(X_T_X_inv)

[[ 4.23638519e-01 -1.15415543e-04]
 [-1.15415543e-04  3.17599920e-08]]


Answer: **The inverse is like the reciprocal of the matrix that was used to generate it. Just like 1/2 is the reciprocal of 2, A^-1 acts like the reciprocal of A.**

6) Use matrix multiplication to calculate $X^TY$.

In [24]:
### YOUR CODE HERE ###

X_T_Y = np.matmul(X_T, Y)

print(X_T_Y)

[[    304041]
 [1113176805]]


7) Use your previous results to calculate the values of the slope and intercept using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

In [40]:
### YOUR CODE HERE ###

B = np.matmul(X_T_X_inv, X_T_Y)

np.set_printoptions(suppress=True)

print(B)

[[368.28214514]
 [  0.26043877]
 [-20.73164463]]


8) Use the OLS function to calculate the slope and intercept and compare your answers.

In [30]:
### YOUR CODE HERE ###

from statsmodels.formula.api import ols

models = ols('Brain ~ Head', data=df).fit()

print(models.params)

Intercept    325.573421
Head           0.263429
dtype: float64


9) Create a new X matrix that includes coluns for both head size and age group.

In [33]:
### YOUR CODE HERE ###
ones = np.repeat(1, len(df)).reshape(-1, 1)
Head = np.array(df['Head']).reshape(-1, 1)
Age = np.array(df['Age']).reshape(-1, 1)

X = np.concatenate((ones, Head, Age), axis=1)

Y = np.array(df['Brain']).reshape(-1, 1)

11) Calculate the values of the intercept and slope terms for head size and age using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

In [39]:
### YOUR CODE HERE ###

X_T = np.transpose(X)

X_T_X = np.matmul(X_T, X)

X_T_X_inv = np.linalg.inv(X_T_X)

X_T_Y = np.matmul(X_T, Y)

B = np.matmul(X_T_X_inv, X_T_Y)

np.set_printoptions(suppress=True)
print(B)

[[368.28214514]
 [  0.26043877]
 [-20.73164463]]


11) Use the OLS function to confirm your answer in 10).

In [38]:
### YOUR CODE HERE ###

from statsmodels.formula.api import ols 

model1 = ols('Brain ~ Head + Age', data=df).fit()

print(model1.params)

Intercept    368.282145
Head           0.260439
Age          -20.731645
dtype: float64


#Use the following information to answer the assignment questions 12) - 16).

The song writing collaboration between John Lennon and Paul McCartney was one of the most productive in music history.  Unlike many other partnerships where one individual wrote lyrics and one wrote music, Lennon and McCartney composed both, and it was decided that any song that was written would be credited to both.  In the beginning of their relationship, many of their songs were truly collabroative.  However, later on, they often worked separately with little to no input from the other.    

Because of extensive reporting on the Beatles over the years, it is generally known if a Lennon-McCartney song was a true collabortion, primarily (or totally) writen by Lennon, or primarily (or totally) written by McCartney.  

However, there are several disputed songs where both Lennon and McCartney at times claimed to be the sole (or primary) composer.

We will now use cosine similarity to determine if *Ticket to Ride* (disputed) is most similar to *From Me to You* (collabortive, not disputed) or *Strawberry Fields* (Lennon, not disputed).

From the Wikipedia article on the Lennon-McCartney Partnership: Lennon said that McCartney's contribution was limited to "the way Ringo played the drums".In Many Years from Now, McCartney said "we sat down and wrote it together ... give him 60 percent of it."

12) Import the text of Strawberry Fields and calculate the freqency of song lyrics using the code below.

In [41]:
### YOUR CODE HERE ###

import pandas as pd

#Strawberry Fields - John Lennon (not disputed)

Strawberry_ = "let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever living is easy with eyes closed misunderstanding all you see its getting hard to be someone but it all works out it doesnt matter much to me let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever no one I think is in my tree I mean it must be high or low that is you cant you know tune in but its all right that is I think its not too bad let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever always no sometimes think but you know I know when it's a dream I think er no I mean er yes but its all wrong that is I think I disagree let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever Strawberry Fields forever Strawberry Fields forever"

Strawberry_df = pd.DataFrame({"Words": Strawberry_.split()})

Strawberry_df.head()

Words
0   let
1    me
2  take
3   you
4  down

In [42]:
Strawberry_df_freq = pd.DataFrame(pd.crosstab(index=Strawberry_df['Words'],columns='count'))

Strawberry_df_freq[0:50]

col_0             count
Words                  
Fields               10
I                     8
Im                    4
Strawberry           10
a                     1
about                 4
all                   4
always                1
and                   4
bad                   1
be                    2
but                   4
cant                  1
cause                 4
closed                1
disagree              1
doesnt                1
down                  4
dream                 1
easy                  1
er                    2
eyes                  1
forever               6
get                   4
getting               1
going                 4
hard                  1
high                  1
hung                  4
in                    2
is                    9
it                    3
it's                  1
its                   4
know                  3
let                   4
living                1
low                   1
matter                1
me                    5
mean                  2
misunderstanding      1
much                  1
must                  1
my                    1
no                    3
not                   1
nothing               8
one                   1
or                    1

13) Import the text of From Me to You and calculate the freqency of song lyrics using the code below.

In [46]:
### YOUR CODE HERE ###

#From Me to You - Lennon and McCartney (not disputed)

Me_ = "if there's anything that you want if there's anything I can do just call on me and Ill send it along with love from me to you Ive got everything that you want like a heart thats oh so true just call on me and Ill send it along with love from me to you Ive got arms that long to hold you and keep you by my side Ive got lips that long to kiss you and keep you satisfied oh if theres anything that you want if theres anything I can do just call on me and Ill send it along with love from me to you from me to you just call on me and Ill send it along with love from me to you Ive got arms that long to hold you and keep you by my side Ive got lips that long to kiss you and keep you satisfied oh if theres anything that you want if theres anything I can do just call on me and Ill send it along with love from me to you to you to you to you"

Me_df = pd.DataFrame({"Words": Me_.split()})

Me_df_freq = pd.DataFrame(pd.crosstab(index=Me_df['Words'],columns='count'))

Me_df_freq[0:50]

col_0       count
Words            
I               3
Ill             5
Ive             5
a               1
along           5
and             9
anything        6
arms            2
by              2
call            5
can             3
do              3
everything      1
from            6
got             5
heart           1
hold            2
if              6
it              5
just            5
keep            4
kiss            2
like            1
lips            2
long            4
love            5
me             11
my              2
oh              3
on              5
satisfied       2
send            5
side            2
so              1
that            8
thats           1
there's         2
theres          4
to             13
true            1
want            4
with            5
you            21

13) Import the text of Ticket to Ride using the code below.

In [44]:
### YOUR CODE HERE ###
Ride_ = "I think Im gonna be sad I think its today yeah the girl thats driving me mad is going away shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care she said that living with me is bringing her down yeah for she would never be free when I was around shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care I dont know why shes ridin so high she ought to think twice she ought to do right by me before she gets to saying goodbye she ought to think twice she ought to do right by me I think Im gonna be sad I think its today yeah the girl thats driving me mad is going away yeah shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care I dont know why shes ridin so high she ought to think twice she ought to do right by me before she gets to saying goodbye she ought to think twice she ought to do right by me she said that living with me is bringing her down yeah for she would never be free when I was around ah shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care my baby dont care my baby dont care my baby dont care my baby dont care my baby dont care my baby dont care"

Ride_df = pd.DataFrame({"Words": Ride_.split()})

Ride_df_freq = pd.DataFrame(pd.crosstab(index=Ride_df['Words'], columns='count'))

Ride_df_freq[0:50]



col_0     count
Words          
I             8
Im            2
a            12
ah            1
around        2
away          2
baby          6
be            4
before        2
bringing      2
but           4
by            4
care         10
do            4
dont         12
down          2
driving       2
for           2
free          2
gets          2
girl          2
going         2
gonna         2
goodbye       2
got          12
her           2
high          2
is            4
its           2
know          2
living        2
mad           2
me            8
my            6
never         2
ought         8
ride         12
ridin         2
right         4
sad           2
said          2
saying        2
she          18
shes         14
so            2
that          2
thats         2
the           2
think         8
ticket       12

14) Concatenate Ticket to Ride and Strawberry Fields and calculate the cosine similarity.

In [45]:
### YOUR CODE HERE ###

from numpy import dot
from numpy.linalg import norm

dfs = [Ride_df_freq, Strawberry_df_freq]

all_words = pd.concat(dfs, axis=1)
all_words = all_words.fillna(0)
all_words.columns = ["Ticket to Ride", "Strawberry Fields"]
all_words[0:50]


cos_sim = dot(all_words["Ticket to Ride"], all_words["Strawberry Fields"])/(norm(all_words["Ticket to Ride"])*norm(all_words["Strawberry Fields"]))

print(cos_sim)



0.324035859004908


15) Concatenate Ticket to Ride and From Me to You and calculate the cosine similarity.

In [47]:
### YOUR CODE HERE ###

from numpy import dot
from numpy.linalg import norm

dfs = [Ride_df_freq, Me_df_freq]

all_words = pd.concat(dfs, axis=1)
all_words = all_words.fillna(0)
all_words.columns = ["Ticket to Ride", "From Me to You"]
all_words[0:50]


cos_sim = dot(all_words["Ticket to Ride"], all_words["From Me to You"])/(norm(all_words["Ticket to Ride"])*norm(all_words["From Me to You"]))

print(cos_sim)

0.2882268853551227


16) What is your conclusion about Ticket to Ride?  Does it appear most similar to Strawberry Fields (Lennon) or From Me to You (collaborative)?

Answer: Ticket to Ride appears to be most similar to Strawberry Fields written by Lennon.