<a href="https://colab.research.google.com/github/badabad/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [153]:
# YOUR WORK HERE
import pandas as pd
import numpy as np
from scipy import stats
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-08-12 14:35:21--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.5’

student.zip.5       100%[===================>]  20.00K  --.-KB/s    in 0.07s   

2020-08-12 14:35:21 (302 KB/s) - ‘student.zip.5’ saved [20478/20478]



In [82]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student-merge.R? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [83]:
mat= pd.read_csv('student-mat.csv', delimiter=';')
mat.isnull().sum()
mat.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [133]:
observed = pd.crosstab(mat['sex'],mat['famrel'])
observed_margins = pd.crosstab(mat['sex'],mat['famrel'],margins=True)
observed_margins

famrel  1   2   3    4    5  All
sex                             
F       5   9  38  107   49  208
M       3   9  30   88   57  187
All     8  18  68  195  106  395

In [134]:
col_sums = observed_margins.iloc[0:2, 5]
col_sums

sex
F    208
M    187
Name: All, dtype: int64

In [135]:
row_sums = observed_margins.iloc[2,:5]
total_total = observed_margins.iloc[2,5]

In [136]:
for row in row_sums:
  print(row)

8
18
68
195
106


In [137]:
expected = []
for row in row_sums:
  expected_row = []
  for col in col_sums:
    expected_v = col*row/total_total
    expected_row.append(expected_v)
  expected.append(expected_row)

expected = np.array(expected)
expected=expected.transpose()
print(expected.shape)
print(expected)

(2, 5)
[[  4.21265823   9.47848101  35.80759494 102.6835443   55.81772152]
 [  3.78734177   8.52151899  32.19240506  92.3164557   50.18227848]]


In [141]:
chi2 = ((observed-expected)**2/expected).sum().sum()
print(chi2)

2.7876556359247564


## (2 rows - 1)(5 col -1) = 4 DOF

## Using a Chi2 calculator, the p value came out to .59, I fail to reject the null hypothesis that sex and family relationships are independent.

In [142]:
observed2 = pd.crosstab(mat['studytime'],mat['freetime'])
observed_margins2 = pd.crosstab(mat['studytime'],mat['freetime'],margins=True)
observed_margins2

freetime    1   2    3    4   5  All
studytime                           
1           2  19   35   29  20  105
2          11  28   82   61  16  198
3           3  11   29   21   1   65
4           3   6   11    4   3   27
All        19  64  157  115  40  395

In [148]:
row_sums2 = observed_margins2.iloc[0:4, 5]
for row in row_sums2:
  print(row)

105
198
65
27


In [149]:
col_sums2 = observed_margins2.iloc[4,:5]
total_total2=observed_margins2.iloc[4,5]
print(total_total2)
for col in col_sums2:
  print(col)

395
19
64
157
115
40


In [151]:
expected2 = []
for row in row_sums2:
  expected_row = []
  for col in col_sums2:
    expected_v = col*row/total_total2
    expected_row.append(expected_v)
  expected2.append(expected_row)

expected2 = np.array(expected2)

print(expected2.shape)
print(expected2)

(4, 5)
[[ 5.05063291 17.01265823 41.73417722 30.56962025 10.63291139]
 [ 9.52405063 32.08101266 78.69873418 57.64556962 20.05063291]
 [ 3.12658228 10.53164557 25.83544304 18.92405063  6.58227848]
 [ 1.29873418  4.37468354 10.73164557  7.86075949  2.73417722]]


In [152]:
chi2_2 = ((observed2-expected2)**2/expected2).sum().sum()
print(chi2_2)

23.530454269130594


(4 rows -1)(5 col -1) = 12 DOF

### With a calculator p value of .02355, I reject the null hypothesis that study time and free time are independent

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [158]:
# YOUR WORK HERE
from scipy import stats
stats.chi2_contingency(observed)

(2.7876556359247564,
 0.5939654443927852,
 4,
 array([[  4.21265823,   9.47848101,  35.80759494, 102.6835443 ,
          55.81772152],
        [  3.78734177,   8.52151899,  32.19240506,  92.3164557 ,
          50.18227848]]))

### I repeated my chi square test on sex and family relationships. I came to the same conclusion: I fail to reject the hypothesis that sex and family relationships are independent. The chi2_contingency returned the same values that I got when I calculated this by hand

## **I realized that I had actually calculated my first two tests by hand. I guess I'll do two scipy chi2 tests and two by hand chi2 tests**

In [159]:
stats.chi2_contingency(observed2)

(23.53045426913059,
 0.023545617681757027,
 12,
 array([[ 5.05063291, 17.01265823, 41.73417722, 30.56962025, 10.63291139],
        [ 9.52405063, 32.08101266, 78.69873418, 57.64556962, 20.05063291],
        [ 3.12658228, 10.53164557, 25.83544304, 18.92405063,  6.58227848],
        [ 1.29873418,  4.37468354, 10.73164557,  7.86075949,  2.73417722]]))

## Running the Scipy test, I got the same results as I did by hand. I still reject the null hypothesis that hours studying and hours of free time are independent

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)