<a href="https://colab.research.google.com/github/Rick1310/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Ricky_Chance%5CLS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from scipy import stats
# Here we read in the dataset

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-08-12 12:59:31--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-08-12 12:59:32 (318 KB/s) - ‘student.zip’ saved [20478/20478]



In [2]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [3]:
df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [4]:
df.describe(exclude='number')

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


# Travel time affects failure rates

# Null Hypothesis
Travel time and failure rates are independent.

# Alternate Hypothesis
Travel time and failure rates are dependent

# Conclusion

Based on a chi stat of 21.124872 and a p value of .01210, I **fail** to reject the null Hypothesis. 

In [28]:
contingency = pd.crosstab(df['freetime'], df['failures'])

contingency

failures    0   1  2  3
freetime               
1          13   5  1  0
2          52   7  4  1
3         134  11  6  6
4          86  20  5  4
5          27   7  1  5

In [29]:
observed_with_margins = pd.crosstab(df['freetime'], df['failures'], margins=True)
observed_with_margins

failures    0   1   2   3  All
freetime                      
1          13   5   1   0   19
2          52   7   4   1   64
3         134  11   6   6  157
4          86  20   5   4  115
5          27   7   1   5   40
All       312  50  17  16  395

In [8]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 21.124872298979813
p value: 0.012107363244231761
dof: 9
expected_frequencies: 
 [[202.99746835  32.53164557  11.06075949  10.41012658]
 [ 84.5164557   13.5443038    4.60506329   4.33417722]
 [ 18.16708861   2.91139241   0.98987342   0.93164557]
 [  6.31898734   1.01265823   0.3443038    0.32405063]]


# Do gender and studytime affect each other?

#Null Hypothesis

Gender and studytime are independent

#Alternate Hypothesis

Gender and studytime are dependent.

# Conclusion

Based on a Chi value of 50.63403 and a p value of .00000000005854045926336989, I **fail** to reject the null hypothesis. 


In [27]:
contingency = pd.crosstab(df['famsize'], df['studytime'])
contingency

studytime   1    2   3   4
famsize                   
GT3        74  131  57  19
LE3        31   67   8   8

In [12]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 50.634037705651764
p value: 5.854045926336989e-11
dof: 3
expected_frequencies: 
 [[ 55.29113924 104.26329114  34.2278481   14.21772152]
 [ 49.70886076  93.73670886  30.7721519   12.78227848]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [13]:
contingency

studytime   1    2   3   4
sex                       
F          27  113  51  17
M          78   85  14  10

In [25]:
col_totals = df['studytime'].value_counts().sort_index().values

col_totals

array([105, 198,  65,  27])

In [26]:
row_totals = df['age'].value_counts().sort_index()
row_totals

15     82
16    104
17     98
18     82
19     24
20      3
21      1
22      1
Name: age, dtype: int64

In [24]:
for row_index, row in enumerate(row_totals):
  for column_index, col in enumerate(col_totals):
    # calculate the expected value
    expected_value = (row*col)/sample_size
    # put that value into the expected value table
    # at the correct location.
    expected[row_index][column_index] = expected_value
    print(expected_value, row_index, column_index)

    expected

21.79746835443038 0 0
27.645569620253166 0 1
26.050632911392405 0 2
21.79746835443038 0 3


IndexError: ignored

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)