<a href="https://colab.research.google.com/github/tranitapalmer/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Tranita_Palmer_LS_DS17_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [1]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

!unzip student.zip

--2020-06-11 01:11:23--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-06-11 01:11:24 (146 KB/s) - ‘student.zip’ saved [20478/20478]

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [0]:
# YOUR WORK HERE
import pandas as pd
import numpy as np
from scipy import stats




In [9]:
df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [10]:
# YOUR WORK HERE
df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [11]:
df['school'].value_counts()

GP    349
MS     46
Name: school, dtype: int64

In [12]:
df['sex'].value_counts()

F    208
M    187
Name: sex, dtype: int64

In [14]:
observed = pd.crosstab(df['school'], df['sex'])

observed

sex       F    M
school          
GP      183  166
MS       25   21

In [15]:
chi2, p_value, dof, expected = stats.chi2_contingency(observed)

print("chi2 statistic", chi2)
print("\np value", p_value)
print("\ndegrees of freedom",dof)
print("\nexpected frequencies table \n", expected)

chi2 statistic 0.007584677753178483

p value 0.9305999299762074

degrees of freedom 1

expected frequencies table 
 [[183.77721519 165.22278481]
 [ 24.22278481  21.77721519]]


In [16]:
df['traveltime'].value_counts()

1    257
2    107
3     23
4      8
Name: traveltime, dtype: int64

In [17]:
df['studytime'].value_counts()

2    198
1    105
3     65
4     27
Name: studytime, dtype: int64

In [18]:
observed = pd.crosstab(df['traveltime'], df['studytime'])

observed

studytime    1    2   3   4
traveltime                 
1           60  133  47  17
2           31   51  16   9
3           11   11   1   0
4            3    3   1   1

In [19]:
chi2, p_value, dof, expected = stats.chi2_contingency(observed)

print("chi2 statistic", chi2)
print("\np value", p_value)
print("\ndegrees of freedom",dof)
print("\nexpected frequencies table \n", expected)

chi2 statistic 11.200170929144969

p value 0.26223746329595793

degrees of freedom 9

expected frequencies table 
 [[ 68.3164557  128.82531646  42.29113924  17.56708861]
 [ 28.44303797  53.63544304  17.60759494   7.31392405]
 [  6.11392405  11.52911392   3.78481013   1.5721519 ]
 [  2.12658228   4.01012658   1.3164557    0.54683544]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [0]:
import pandas as pd
import numpy as np
from scipy import stats


In [24]:
# YOUR WORK HERE


df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()


(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [25]:
observed = pd.crosstab(df['school'], df['sex'])

observed

sex       F    M
school          
GP      183  166
MS       25   21

In [26]:
observed_margins = pd.crosstab(df['school'], df['sex'], margins=True)
observed_margins

sex       F    M  All
school               
GP      183  166  349
MS       25   21   46
All     208  187  395

In [50]:
row_sums = observed_margins.iloc[0:3, 3:].values
row_sums = row_sums.T

row_sums

array([], shape=(0, 3), dtype=int64)

In [38]:
col_sums = observed_margins.iloc[2:, 0:3].values
col_sums = col_sums[0]

col_sums

array([208, 187, 395])

In [39]:
total_total = df.shape[0]

total_total

395

In [40]:
expected = []
for i in range(len(row_sums)):
  expected_row = []
  for column in col_sums:
    expected_val = column*row_sums[i]/total_total
    expected_row.append(expected_val)
  expected.append(expected_row)

expected = np.array(expected)
print(expected.shape)  
print(expected)

(0,)
[]


In [56]:
chi2, p_value, dof, expected = stats.chi2_contingency(observed)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 0.007584677753178483
p value 0.9305999299762074
degrees of freedom 1
expected frequencies table [[183.77721519 165.22278481]
 [ 24.22278481  21.77721519]]


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [0]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)