<a href="https://colab.research.google.com/github/davidxu90/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("student-mat.csv", delimiter = ";")
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [6]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [12]:
from scipy import stats

chi2, p_value, dof, expected = stats.chi2_contingency(pd.crosstab(df['studytime'], df['freetime']))

print("chi^2:", chi2)
print("p:", p_value)
print("degrees of freedom:",dof)
print("expected frequencies table:\n", expected)

chi^2: 23.53045426913059
p: 0.023545617681757027
degrees of freedom: 12
expected frequencies table:
 [[ 5.05063291 17.01265823 41.73417722 30.56962025 10.63291139]
 [ 9.52405063 32.08101266 78.69873418 57.64556962 20.05063291]
 [ 3.12658228 10.53164557 25.83544304 18.92405063  6.58227848]
 [ 1.29873418  4.37468354 10.73164557  7.86075949  2.73417722]]


In [15]:
chi2, p_value, dof, expected = stats.chi2_contingency(pd.crosstab(df['traveltime'], df['health']))

print("chi^2:", chi2)
print("p:", p_value)
print("degrees of freedom:",dof)
print("expected frequencies table:\n", expected)

chi^2: 6.782234593768585
p: 0.871662445638273
degrees of freedom: 12
expected frequencies table:
 [[30.57974684 29.27848101 59.20759494 42.94177215 94.99240506]
 [12.73164557 12.18987342 24.65063291 17.87848101 39.54936709]
 [ 2.73670886  2.62025316  5.29873418  3.84303797  8.50126582]
 [ 0.95189873  0.91139241  1.84303797  1.33670886  2.95696203]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [28]:
observed = pd.crosstab(df['studytime'], df['freetime'])

row_totals = df['freetime'].value_counts().sort_index().values
col_totals = df['studytime'].value_counts().sort_index().values

sample_size = df.shape[0]

expected = np.zeros(shape = (len(col_totals), len(row_totals)))

for row_position, col in enumerate(col_totals):
  for column_position, row in enumerate(row_totals):
    expected_value = (row * col) / sample_size
    expected[row_position][column_position] = expected_value

chi2 = ((observed - expected) ** 2 / expected).sum().sum()

print("chi^2:", chi2)
print("expected frequencies table:\n", expected)

chi^2: 23.530454269130594
expected frequencies table:
 [[ 5.05063291 17.01265823 41.73417722 30.56962025 10.63291139]
 [ 9.52405063 32.08101266 78.69873418 57.64556962 20.05063291]
 [ 3.12658228 10.53164557 25.83544304 18.92405063  6.58227848]
 [ 1.29873418  4.37468354 10.73164557  7.86075949  2.73417722]]


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)