<a href="https://colab.research.google.com/github/max-moore/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/module2/LS_DS18_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [ ]:
# YOUR WORK HERE

import numpy as np
import pandas as pd
from scipy import stats

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

In [ ]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [ ]:
df = pd.read_csv('student-mat.csv', sep=';')

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
# YOUR WORK HERE

# Creating contingency tables

observed = pd.crosstab(df['Dalc'],df['failures'])
observed2 = pd.crosstab(df['famrel'], df['absences'])

# Assigning and printing chi2 value, p value, depth of freedom, 
# and expected frequencies

chi2, p_value, dof, expected = stats.chi2_contingency(observed)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table \n", expected)

chi2, p_value, dof, expected = stats.chi2_contingency(observed2)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table \n", expected)

# I think the relationships here make a certain amount of sense
# Frankly, I was expecting more of a relation between family relations and 
# absences, but I guess this still makes a certain amount of sense - school
# might be a respite from family for some students or a stress point for others
# We fail to reject the null hypothesis for the first contingency table

# Somewhat unsurprisingly, the relationship between workday alcohol consumption
# and failures is statistically significant
# We reject the null hypothesis for the second contingency table

chi2 statistic 22.613784416016074
p value 0.031189577855521403
degrees of freedom 12
expected frequencies table 
 [[218.00506329  34.93670886  11.87848101  11.17974684]
 [ 59.24050633   9.49367089   3.2278481    3.03797468]
 [ 20.53670886   3.29113924   1.11898734   1.05316456]
 [  7.10886076   1.13924051   0.38734177   0.36455696]
 [  7.10886076   1.13924051   0.38734177   0.36455696]]
chi2 statistic 102.13915844876783
p value 0.9747839201385753
degrees of freedom 132
expected frequencies table 
 [[2.32911392e+00 6.07594937e-02 1.31645570e+00 1.62025316e-01
  1.07341772e+00 1.01265823e-01 6.27848101e-01 1.41772152e-01
  4.45569620e-01 6.07594937e-02 3.44303797e-01 6.07594937e-02
  2.43037975e-01 6.07594937e-02 2.43037975e-01 6.07594937e-02
  1.41772152e-01 2.02531646e-02 1.01265823e-01 2.02531646e-02
  8.10126582e-02 2.02531646e-02 6.07594937e-02 2.02531646e-02
  2.02531646e-02 2.02531646e-02 2.02531646e-02 2.02531646e-02
  2.02531646e-02 2.02531646e-02 2.02531646e-02 2.02531646e-02
 

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
# YOUR WORK HERE

# Contingency table

contingency = pd.crosstab(df['Dalc'],df['failures'], margins=True)

contingency

failures    0   1   2   3  All
Dalc                          
1         232  29   7   8  276
2          50  12   8   5   75
3          17   6   1   2   26
4           6   2   1   0    9
5           7   1   0   1    9
All       312  50  17  16  395

In [ ]:
# Sorting row totals

row_totals = df['failures'].value_counts().sort_index().values

row_totals

array([312,  50,  17,  16])

In [ ]:
# Sorting column totals

col_totals = df['Dalc'].value_counts().sort_index().values

col_totals

array([276,  75,  26,   9,   9])

In [ ]:
# Amount of observations (?)

sample_size = df.shape[0]

sample_size

395

In [ ]:
# Template array for expected values

expected = np.array([[0.0, 0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0, 0.0],])

# Assigning values to expected values array

for row_position, col in enumerate(col_totals):
  for column_position, row in enumerate(row_totals):
    expected_value = (row*col) / sample_size
    expected[row_position][column_position] = expected_value

expected

array([[218.00506329,  34.93670886,  11.87848101,  11.17974684],
       [ 59.24050633,   9.49367089,   3.2278481 ,   3.03797468],
       [ 20.53670886,   3.29113924,   1.11898734,   1.05316456],
       [  7.10886076,   1.13924051,   0.38734177,   0.36455696],
       [  7.10886076,   1.13924051,   0.38734177,   0.36455696]])

In [ ]:
# Obtaining Chi2 statistic

chi2 = ((observed - expected)**2 / expected).sum().sum()

chi2

22.613784416016074

In [ ]:
# Obtaining Degrees of Freedom

dof = (row_totals.size - 1) * (col_totals.size - 1)

dof

12

In [ ]:
# Used the University of Iowa Applet to get p value from chi2

p_value = 0.03119

In [ ]:
# Print everything we need to see

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table \n", expected)

chi2 statistic 22.613784416016074
p value 0.03119
degrees of freedom 12
expected frequencies table 
 [[218.00506329  34.93670886  11.87848101  11.17974684]
 [ 59.24050633   9.49367089   3.2278481    3.03797468]
 [ 20.53670886   3.29113924   1.11898734   1.05316456]
 [  7.10886076   1.13924051   0.38734177   0.36455696]
 [  7.10886076   1.13924051   0.38734177   0.36455696]]


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)