<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [0]:
##### Your Code Here #####

import numpy as np

np.random.seed( 16)

#x = np.array( ([0, 0, 1, 0, 1, 1, 0],
#               [0, 1, 0, 1, 0, 1, 0],
#               [1, 1, 1, 0, 0, 1, 0]
#), dtype= int)

x = np.array( ([0, 0, 1],
               [0, 1, 1],
               [1, 0, 1],
               [0, 1, 0],
               [1, 0, 0],
               [1, 1, 1],
               [0, 0, 0]
), dtype= int)

y = np.array( ([0, 1, 1, 1, 1, 0, 0]
), dtype= int)


class nNetwork:

    def __init__( self):
        # Arch setup
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1

        # Weights init
        self.weight0 = np.random.randn( self.inputs, self.hiddenNodes)
        self.weight1 = np.random.randn( self.hiddenNodes, self.outputNodes)

    def sigmoid( self, s):
        return 1 / (1 + np.exp( -s))

    def sigmoidPrime( self, s):
        sx = self.sigmoid( s)
        return sx * (1 - sx)

    def feedForward( self, x):
        """ Calculate the NN inference using Feed Forward """

        # dot product of X and input/hidden weights > sigmoid of that product > 
        # dot product of that sigmoid result and hidden/output weights > 
        # sigmoid of that product
        self.hiddenSum = np.dot( x, self.weight0)
        self.activateHidden = self.sigmoid( self.hiddenSum)
        self.outputSum = np.dot( self.activateHidden, self.weight1)
        self.activateOutput = self.sigmoid( self.outputSum)

        return self.activateOutput

    def backward( self, x, y, o):
        """ Back prop through the Network """

        self.oError = y - o     # Error in the output
        
        # Apply derivative of sigmoid to error
        self.oDelta = self.oError * self.sigmoidPrime( o)

        # z2 error: how much were our output layer weights off?
        self.z2Error = self.oDelta.dot( self.weight1.T)

        # z2 delta: how much were the weights off? (what was their delta?)
        self.z2Delta = self.z2Error * self.sigmoidPrime( self.activateHidden)

        # Adjust first set
        self.weight0 += x.T.dot( self.z2Delta)
        # Adjust second set
        self.weight1 += self.activateHidden.T.dot( self.oDelta)

    def train( self, X, y):
        o = self.feedForward( x)
        self.backward( x, y, o)


In [31]:
print("Layer 1 weights: \n", nn.weight0)
print("Layer 2 weights: \n", nn.weight1)

Layer 1 weights: 
 [[ 1.27354347  1.07974786  0.64840236  0.55642014]
 [ 0.23353755 -1.07884538 -1.18196103 -0.70324008]
 [-0.63851589 -0.84206994 -1.33817457  0.57970657]]
Layer 2 weights: 
 [[ 0.53641445]
 [ 1.54303444]
 [ 1.67433222]
 [-0.63928976]]


In [55]:
nn = nNetwork()
output = nn.feedForward( x)
print("\ninput\n", x)
print("\noutput\n", output)


input
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]

output
 [[0.14106553]
 [0.05519091]
 [0.06752562]
 [0.04873995]
 [0.06484601]
 [0.05009404]
 [0.11457219]]


In [56]:
error = y[0] - output
error

array([[-0.14106553],
       [-0.05519091],
       [-0.06752562],
       [-0.04873995],
       [-0.06484601],
       [-0.05009404],
       [-0.11457219]])

In [57]:
nn = nNetwork()
nn.train( x, y)

ValueError: ignored

In [0]:
# I
# Can't
# With
# This
# Error
# Right
# Now
# ....

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [0]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [0]:
# input image dimensions
imgRows, imgCols = 28, 28

In [0]:
# the data, split between train and test sets
(xTrain, yTrain), (xTest, yTest) = mnist.load_data()

In [0]:
xTrain = xTrain.reshape(xTrain.shape[0], imgRows * imgCols)
xTest = xTest.reshape(xTest.shape[0], imgRows * imgCols)

# Normalize Our Data
xTrain = xTrain / 255
xTest = xTest / 255

In [0]:
# Now the data should be in a format you're more familiar with

In [114]:
xTrain.shape, xTest.shape, yTrain.shape, yTest.shape

((60000, 784), (10000, 784), (60000,), (10000,))

In [0]:
# FOR TESTING EXPEDIENCE    (1% train/test observation samples)
#xTrain, garbage = train_test_split( xTrain, train_size= .01)
#xTest, garbage = train_test_split( xTest, train_size= .01)
#yTrain, garbage = train_test_split( yTrain, train_size= .01)
#yTest, garbage = train_test_split( yTest, train_size= .01)

In [100]:
xTrain.shape, xTest.shape, yTrain.shape, yTest.shape

((600, 784), (100, 784), (600,), (100,))

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [0]:
#import numpy as np
#
#yTemp = np.zeros(yTrain.shape)
#yTemp[np.where(yTrain == 0.0)[0]] = 1
#yTrain = yTemp
#
#yTemp = np.zeros(yTest.shape)
#yTemp[np.where(yTest == 0.0)[0]] = 1
#yTest = yTemp

In [0]:
# one-hot encode targets, 10 classes because 10 digits (0-9)
yTrain = to_categorical( yTrain, num_classes= 10)
yTest = to_categorical( yTest, num_classes= 10)

In [65]:
# A Nice Binary target for ya to work with
#yTrain

array([0., 1., 0., ..., 0., 0., 0.])

In [116]:
# A Nice Binary Target for us ta work with
yTrain

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [0]:
# Also, it looks pretty sparse... just sayin....

In [0]:
madel = Sequential()
madel.add( Dense( 256, input_shape= (784,)))    # Dense is roughly equal to the sigmoid( dot( x, weight) + bias) method we've been using, 
                                                # -- accepts input arrays shaped (*,784), and outputs arrays shaped (*,256) to next (hidden) layer
madel.add( Activation( "relu"))                 # select activation function (sigmoid, relu, etc) to pass to next layer
madel.add( Dropout( .5))                        # drops x%, prevents over-fitting
madel.add( Dense( 10))                          # passes array shaped (*, 10) to next layer
madel.add( Activation( "softmax"))              # Softmax normalizes output into a probability distribution 
#                       ^  ^  ^                 # -- (all 10 output values (passed from preceding Dense) exist between 0,1 and add up to 1, cumulatively)
        # STRREEEEEETCH GOOOOOOOOOALSSS #

In [118]:
# Checking information
madel.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 256)               200960    
_________________________________________________________________
activation_2 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                2570      
_________________________________________________________________
activation_3 (Activation)    (None, 10)                0         
Total params: 203,530
Trainable params: 203,530
Non-trainable params: 0
_________________________________________________________________


In [0]:
# compile model (maaaaadel (it's from Boston..)) for training
madel.compile( loss= "categorical_crossentropy",    # catCE measures the average number of bits needed to identify an event from the set
               optimizer= Adam(),                   # stochastic, gradient-based; most excellent for sparse gradients (which this set is)
               metrics= ["accuracy"]                # how often predictions match labels... "accuracy" ¯\_(ツ)_/¯
)                           # STRREEEEEETCH GOOOOOOOOOALSSS #

### Estimating Your `net

In [120]:
##### Your Code Here #####

###     MAGIC PART     ###

fitBit = madel.fit( xTrain, yTrain,
                    batch_size= 256,
                    epochs= 32,
                    verbose= 1,
                    validation_data= ( xTest, yTest)
)                           # STRREEEEEETCH GOOOOOOOOOALSSS #

Train on 60000 samples, validate on 10000 samples
Epoch 1/32
60000/60000 [==============================] - 3s 44us/sample - loss: 0.4791 - acc: 0.8602 - val_loss: 0.2140 - val_acc: 0.9404
Epoch 2/32
60000/60000 [==============================] - 3s 44us/sample - loss: 0.2311 - acc: 0.9330 - val_loss: 0.1527 - val_acc: 0.9563
Epoch 3/32
60000/60000 [==============================] - 3s 42us/sample - loss: 0.1806 - acc: 0.9477 - val_loss: 0.1265 - val_acc: 0.9634
Epoch 4/32
60000/60000 [==============================] - 3s 44us/sample - loss: 0.1505 - acc: 0.9560 - val_loss: 0.1088 - val_acc: 0.9680
Epoch 5/32
60000/60000 [==============================] - 3s 46us/sample - loss: 0.1320 - acc: 0.9613 - val_loss: 0.0968 - val_acc: 0.9717
Epoch 6/32
60000/60000 [==============================] - 3s 46us/sample - loss: 0.1166 - acc: 0.9657 - val_loss: 0.0876 - val_acc: 0.9746
Epoch 7/32
60000/60000 [==============================] - 3s 46us/sample - loss: 0.1052 - acc: 0.9689 - val_loss: 0.

In [122]:
scooooore = madel.evaluate( xTest, yTest, verbose= 1)

10000/10000 [==============================] - 0s 42us/sample - loss: 0.0597 - acc: 0.9837


## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?